/* Per-customer intelligence data — financial, news, decision unit, competitors */

window.LOGOS = {
  "CI Financial":     { kind:"shield",   bg:"#0F2A6B", fg:"#F5C453", mark:"CI", style:"finance" },
  "Logistec Corporation":      { kind:"wave",     bg:"#0E5C8C", fg:"#7FD0F2", mark:"LG", style:"transport" },
  "Rush University System for Health":{ kind:"cross",    bg:"#0E7561", fg:"#A8E6D2", mark:"RU", style:"health" },
  "MAPFRE":      { kind:"diamond",  bg:"#5A1A4D", fg:"#F0C7E2", mark:"MP", style:"insurance" },
  "MAHLE":     { kind:"gear",     bg:"#1F2937", fg:"#F59E0B", mark:"MH", style:"industrial" },
  "Aritzia":          { kind:"sun",      bg:"#B45309", fg:"#FDE68A", mark:"AZ", style:"retail" },
  "NOS":            { kind:"signal",   bg:"#7C2D12", fg:"#FCA5A5", mark:"NS", style:"telecom" },
  "DNB Bank":             { kind:"star",     bg:"#0B3D91", fg:"#9BC4FF", mark:"DN", style:"bank" },
};

/* Stock tickers (mock). Each is 16 quarter-end points + meta. */
const sparkSeries = (start, vol, drift, n=16) => {
  let v = start; const out = [v];
  for (let i=1;i<n;i++) { v = Math.max(1, v + drift + (Math.sin(i*1.7)+Math.cos(i*0.9))*vol); out.push(+v.toFixed(2)); }
  return out;
};

window.INTEL = {
  "CI Financial": {
    ticker:"CIX.TO", exchange:"TSX", price:48.72, change:+1.84,
    series: sparkSeries(36, 1.4, 0.85),
    marketCap:"$12.1B", revenue:"$1.21B", revenueGrowth:"+8.4%",
    ebitda:"$284M", ebitdaMargin:"23.5%",
    debt:"$420M", cash:"$680M",
    creditRating:"A-", ratingAgency:"S&P", ratingTrend:"stable",
    employees:2548, employeeGrowth:"+6.2%",
    headcountSeries: [2200,2240,2290,2340,2410,2455,2510,2548],
    fundingStatus:"Public",
    news:[
      { src:"Bloomberg",   t:"CI Financial reports Q1 beat, raises FY guidance on wealth platform push", at:"2h", sent:"pos", url:"#" },
      { src:"Reuters",     t:"CIO Michael Johnson hints at 5-yr cloud modernization roadmap", at:"1d", sent:"pos", url:"#" },
      { src:"The Globe",   t:"CI Financial commits C$120M to cyber resilience after OSFI advisory", at:"3d", sent:"pos", url:"#" },
      { src:"Crunchbase",  t:"Acme acquires fintech app Lattice for stated $48M", at:"6d", sent:"neu", url:"#" },
    ],
    hiring:[
      { role:"VP, Cloud Platform",        team:"IT", n:1, since:"12d", urgent:true },
      { role:"Senior Cloud Architect",    team:"Infra", n:3, since:"1mo" },
      { role:"Identity Engineer (Entra)", team:"Security", n:2, since:"3w" },
      { role:"M365 Admin",                team:"Workplace", n:4, since:"2w" },
    ],
    triggers:[
      { kind:"funding",   text:"Q1 earnings beat — discretionary IT spend re-opened", weight:9 },
      { kind:"reg",       text:"OSFI B-13 third-party risk reporting due Sep 2026", weight:8 },
      { kind:"executive", text:"New CIO Michael Johnson — 90 days in seat", weight:7 },
      { kind:"tech",      text:"Public RFP for SOC services (closed Apr 2026, you bid)", weight:9 },
      { kind:"deal",      text:"Acquired Lattice — needs M&A IT integration", weight:6 },
    ],
    decisionUnit:[
      { name:"Michael Johnson", role:"CIO",                 init:"MJ", power:"Decision",    sent:"warm", weight:0.92 },
      { name:"Sarah Patel",     role:"IT Security Manager", init:"SP", power:"Champion",    sent:"hot",  weight:0.88 },
      { name:"David Liang",     role:"Infra Director",      init:"DL", power:"Influencer",  sent:"warm", weight:0.74 },
      { name:"Rachel Gomez",    role:"VP Procurement",      init:"RG", power:"Gatekeeper",  sent:"cold", weight:0.45 },
      { name:"Edward Cho",      role:"CFO",                 init:"EC", power:"Approver",    sent:"neutral", weight:0.62 },
    ],
    competitors:[
      { name:"Mantu",       us:true, score:[82,78,71,84,90,76], price:"$1.24M", strength:"Identity & MSP depth", color:"var(--brand-primary)" },
      { name:"Accenture",   score:[88,84,90,72,68,90], price:"$1.55M", strength:"Brand, scale", color:"#7C3AED" },
      { name:"DXC",         score:[70,72,80,68,74,78], price:"$1.10M", strength:"Pricing",     color:"#0E7490" },
      { name:"Local incumbent", score:[55,68,40,82,88,52], price:"$0.92M", strength:"Relationships", color:"#9A6500" },
    ],
    radarAxes:["Tech depth","Delivery","Scale","Local presence","Relationships","Price"],
    win:{ probability:65, breakdown:[
      { f:"Champion engagement (Sarah Patel — 14 touches)", w:+18 },
      { f:"Tech fit vs requirement (94%)",                  w:+15 },
      { f:"On-time RFP responses",                          w:+9 },
      { f:"Pricing 11% above incumbent",                    w:-12 },
      { f:"No CFO meeting yet",                             w:-8 },
      { f:"Renewal cycle aligned (Mar)",                    w:+7 },
    ]},
  },
  /* lighter records for the other customers — shared shape */
  "Logistec Corporation":      { ticker:"PRIV", exchange:"Private", price:null, change:0, series:sparkSeries(20,0.7,0.2),
    marketCap:"—", revenue:"$184M", revenueGrowth:"+11.0%", ebitda:"$22M", ebitdaMargin:"12.0%",
    debt:"$58M", cash:"$31M", creditRating:"BB+", ratingAgency:"Moody's", ratingTrend:"positive",
    employees:812, employeeGrowth:"+4.1%", headcountSeries:[720,735,760,780,795,803,810,812],
    fundingStatus:"PE-backed (Onex, 2022)",
    news:[
      { src:"PitchBook", t:"Logistec wins multi-year contract with Port of Montreal cold chain", at:"4h", sent:"pos" },
      { src:"LinkedIn",  t:"Helena Voss promoted to CISO from Head of IT", at:"2d", sent:"pos" },
      { src:"The Logic", t:"Sokoman family considers Logistec stake review in 2027", at:"1w", sent:"neu" },
    ],
    hiring:[{ role:"Compliance Lead", team:"Risk", n:1, since:"3w", urgent:true }],
    triggers:[
      { kind:"executive", text:"New CISO — first 100 days, hungry for wins", weight:9 },
      { kind:"reg",       text:"Enterprise customer mandates SOC 2 by Q4", weight:10 },
      { kind:"deal",      text:"Cold-chain contract win → must scale fast", weight:7 },
    ],
    decisionUnit:[
      { name:"Helena Voss",  role:"CISO",        init:"HV", power:"Decision", sent:"hot",     weight:0.86 },
      { name:"Marc DuBois",  role:"COO",         init:"MD", power:"Approver", sent:"warm",    weight:0.7 },
      { name:"Inès Tremblay",role:"VP Finance",  init:"IT", power:"Approver", sent:"neutral", weight:0.55 },
    ],
    competitors:[
      { name:"Mantu", us:true, score:[78,72,55,80,72,80], price:"$320K", strength:"Speed", color:"var(--brand-primary)" },
      { name:"Big-4 Advisory",   score:[80,68,90,70,60,55], price:"$520K", strength:"Audit-trust", color:"#7C3AED" },
    ],
    radarAxes:["Tech depth","Delivery","Scale","Local presence","Relationships","Price"],
    win:{ probability:35, breakdown:[
      { f:"CISO is champion",            w:+14 },
      { f:"Aggressive timeline (9 mo)",  w:-10 },
      { f:"No prior relationship",       w:-9 },
      { f:"Fixed-fee model fits buyer",  w:+8 },
    ]},
  },
  "Rush University System for Health":{ ticker:"PRIV", exchange:"Private (non-profit)", price:112.48, change:-0.42, series:sparkSeries(95,2.4,1.0),
    marketCap:"$8.4B", revenue:"$2.9B", revenueGrowth:"+5.1%", ebitda:"$338M", ebitdaMargin:"11.7%",
    debt:"$1.2B", cash:"$430M", creditRating:"A", ratingAgency:"S&P", ratingTrend:"stable",
    employees:6240, employeeGrowth:"+2.8%", headcountSeries:[5800,5870,5950,6010,6090,6160,6210,6240],
    fundingStatus:"Public",
    news:[
      { src:"Modern Healthcare", t:"Rush University to consolidate 4 EHR instances onto Epic by 2027", at:"1d", sent:"pos" },
      { src:"Becker's",          t:"CMS audit flags PHI handling at 2 hospitals", at:"4d", sent:"neg" },
      { src:"Bloomberg",         t:"Rush University approves $480M cap-ex for cloud + AI diagnostics", at:"2w", sent:"pos" },
    ],
    hiring:[
      { role:"Cloud SRE",       team:"Platform", n:5, since:"2w" },
      { role:"HIPAA Compliance",team:"Risk",     n:2, since:"5w" },
    ],
    triggers:[
      { kind:"reg",   text:"CMS audit finding — remediation due Aug 2026", weight:10 },
      { kind:"tech",  text:"Epic on Azure mandate from board", weight:9 },
      { kind:"deal",  text:"Cap-ex approved — budget exists", weight:9 },
    ],
    decisionUnit:[
      { name:"Anil Rajan",      role:"VP Technology", init:"AR", power:"Decision",   sent:"hot",  weight:0.94 },
      { name:"Dr. Lena Park",   role:"CMIO",          init:"LP", power:"Influencer", sent:"warm", weight:0.78 },
      { name:"Greg Halvorsen",  role:"CFO",           init:"GH", power:"Approver",   sent:"warm", weight:0.72 },
    ],
    competitors:[
      { name:"Mantu",   us:true, score:[88,85,80,72,78,72], price:"$4.80M", strength:"Healthcare cloud", color:"var(--brand-primary)" },
      { name:"Deloitte",         score:[85,80,92,80,82,68], price:"$5.40M", strength:"Healthcare practice", color:"#7C3AED" },
      { name:"HCL",              score:[78,82,85,60,55,90], price:"$3.95M", strength:"Cost",  color:"#0E7490" },
    ],
    radarAxes:["Tech depth","Delivery","Scale","Local presence","Relationships","Price"],
    win:{ probability:78, breakdown:[
      { f:"Champion VP-Tech aligned",   w:+22 },
      { f:"Epic+Azure reference deal",  w:+18 },
      { f:"Audit deadline pressure",    w:+12 },
      { f:"HCL undercutting on price",  w:-9 },
    ]},
  },
  "MAPFRE": { ticker:"MAP.MC", exchange:"BME", price:14.10, change:+0.06, series:sparkSeries(13,0.4,0.05),
    marketCap:"€3.1B", revenue:"€812M", revenueGrowth:"+1.2%", ebitda:"€96M", ebitdaMargin:"11.8%",
    debt:"€220M", cash:"€118M", creditRating:"BBB", ratingAgency:"Fitch", ratingTrend:"negative",
    employees:4012, employeeGrowth:"-0.8%", headcountSeries:[4080,4070,4055,4040,4030,4022,4015,4012],
    fundingStatus:"Public",
    news:[
      { src:"Expansión", t:"MAPFRE explores cost-cutting after Q4 miss; IT budget under review", at:"3d", sent:"neg" },
      { src:"DORA Watch",t:"Spanish insurers face DORA 2026 deadline — IAM gap flagged", at:"1w", sent:"neu" },
    ],
    hiring:[ { role:"IT Director", team:"IT", n:1, since:"6w" } ],
    triggers:[
      { kind:"reg",       text:"DORA + NIS2 — IAM gap is audit-blocker", weight:9 },
      { kind:"executive", text:"CFO-led cost review; CIO seat vacant", weight:6 },
    ],
    decisionUnit:[
      { name:"Carmen López", role:"Identity Architect", init:"CL", power:"Champion",   sent:"hot",     weight:0.74 },
      { name:"(vacant)",     role:"CIO",                init:"··", power:"Decision",   sent:"unknown", weight:0.4 },
      { name:"Tomás Vega",   role:"CFO",                init:"TV", power:"Approver",   sent:"cold",    weight:0.55 },
    ],
    competitors:[
      { name:"Mantu", us:true, score:[72,68,55,82,55,75], price:"€680K", strength:"IAM expertise", color:"var(--brand-primary)" },
      { name:"PwC",            score:[78,75,90,85,72,55], price:"€920K", strength:"Big-4 trust",   color:"#7C3AED" },
    ],
    radarAxes:["Tech depth","Delivery","Scale","Local presence","Relationships","Price"],
    win:{ probability:20, breakdown:[
      { f:"No clear decision maker (CIO vacant)", w:-18 },
      { f:"Champion is technical, not buyer",     w:-7 },
      { f:"Regulatory deadline gives urgency",    w:+10 },
      { f:"Budget squeeze",                        w:-9 },
    ]},
  },
  "MAHLE": { ticker:"PRIV", exchange:"Private (foundation)", price:78.65, change:+0.92, series:sparkSeries(64,1.8,0.55),
    marketCap:"€5.6B", revenue:"€2.2B", revenueGrowth:"+3.4%", ebitda:"€264M", ebitdaMargin:"12.0%",
    debt:"€680M", cash:"€340M", creditRating:"BBB+", ratingAgency:"S&P", ratingTrend:"stable",
    employees:12104, employeeGrowth:"+1.6%", headcountSeries:[11800,11860,11920,11980,12040,12080,12095,12104],
    fundingStatus:"Public",
    news:[
      { src:"Handelsblatt", t:"Loomis to invest €180M in OT cybersecurity after ransomware near-miss", at:"1d", sent:"pos" },
      { src:"Manufacturing.net",t:"Loomis CEO: \"Our 22 plants must speak one network language\"", at:"5d", sent:"pos" },
    ],
    hiring:[ { role:"OT Security Lead", team:"Plant IT", n:2, since:"3w", urgent:true } ],
    triggers:[
      { kind:"tech", text:"Ransomware near-miss → board mandate for OT segmentation", weight:10 },
      { kind:"reg",  text:"NIS2 deadline Oct 2026 for critical infrastructure", weight:9 },
    ],
    decisionUnit:[
      { name:"Heinrich Müller", role:"Head of Plant IT", init:"HM", power:"Champion",   sent:"hot",  weight:0.82 },
      { name:"Anke Schulz",     role:"CIO",              init:"AS", power:"Decision",   sent:"warm", weight:0.78 },
      { name:"Werner Klein",    role:"CFO",              init:"WK", power:"Approver",   sent:"neutral", weight:0.6 },
    ],
    competitors:[
      { name:"Mantu",  us:true, score:[80,76,68,82,72,72], price:"€2.15M", strength:"OT/IT bridge", color:"var(--brand-primary)" },
      { name:"Capgemini",      score:[82,80,90,88,78,68], price:"€2.55M", strength:"Local/EU",    color:"#7C3AED" },
      { name:"Atos",           score:[68,72,80,86,80,75], price:"€2.05M", strength:"Existing relationship", color:"#0E7490" },
    ],
    radarAxes:["Tech depth","Delivery","Scale","Local presence","Relationships","Price"],
    win:{ probability:55, breakdown:[
      { f:"Strong technical fit (OT/IT)",          w:+16 },
      { f:"Atos has existing master agreement",    w:-10 },
      { f:"NIS2 deadline gives urgency",            w:+9 },
      { f:"Local partner needed in Stuttgart",     w:-5 },
    ]},
  },
  "Aritzia":      { ticker:"ATZ.TO", exchange:"TSX", price:38.42, change:+0.61, series:sparkSeries(35,1.1,0.45),
    marketCap:"C$4.4B", revenue:"C$2.5B", revenueGrowth:"+11.6%", ebitda:"C$330M", ebitdaMargin:"13.2%",
    debt:"C$0", cash:"C$220M", creditRating:"BBB", ratingAgency:"S&P", ratingTrend:"stable",
    employees:9120, employeeGrowth:"+6.2%", headcountSeries:[8200,8400,8600,8780,8900,9000,9080,9120],
    fundingStatus:"Public",
    news:[
      { src:"Retail Dive", t:"Aritzia opens 8 new flagships, accelerates e-commerce platform", at:"3d", sent:"neu" },
    ],
    hiring:[],
    triggers:[
      { kind:"tech", text:"Endpoint refresh — POS lifecycle end-of-life", weight:8 },
      { kind:"deal", text:"Awarded — kickoff scheduled", weight:10 },
    ],
    decisionUnit:[
      { name:"Olivia Reyes", role:"VP Operations", init:"OR", power:"Decision", sent:"hot", weight:0.9 },
    ],
    competitors:[ { name:"Mantu", us:true, score:[78,84,72,88,90,80], price:"$410K", strength:"Speed", color:"var(--brand-primary)" } ],
    radarAxes:["Tech depth","Delivery","Scale","Local presence","Relationships","Price"],
    win:{ probability:100, breakdown:[ { f:"Won — kickoff next week", w:+100 } ]},
  },
  "NOS":        { ticker:"NOS.LS", exchange:"Euronext Lisbon", price:3.02, change:-0.04, series:sparkSeries(4,0.2,-0.05),
    marketCap:"€680M", revenue:"€1.4B", revenueGrowth:"-1.8%", ebitda:"€124M", ebitdaMargin:"8.9%",
    debt:"€890M", cash:"€88M", creditRating:"BB-", ratingAgency:"Fitch", ratingTrend:"negative",
    employees:9105, employeeGrowth:"-3.2%", headcountSeries:[9450,9410,9360,9300,9240,9180,9140,9105],
    fundingStatus:"Public",
    news:[
      { src:"Telecoms.com", t:"NOS loses SOC build-out tender to NTT DATA", at:"2w", sent:"neg" },
    ],
    hiring:[],
    triggers:[ { kind:"deal", text:"Lost on price — closed", weight:1 } ],
    decisionUnit:[],
    competitors:[ { name:"Mantu", us:true, score:[60,64,55,72,55,55], price:"€1.90M", strength:"—", color:"var(--brand-primary)" }, { name:"NTT DATA", score:[78,80,90,78,68,82], price:"€1.55M", strength:"Won", color:"#7C3AED" } ],
    radarAxes:["Tech depth","Delivery","Scale","Local presence","Relationships","Price"],
    win:{ probability:0, breakdown:[ { f:"Lost on price (-19%)", w:-100 } ]},
  },
  "DNB Bank":         { ticker:"DNB.OL", exchange:"Oslo Børs", price:84.20, change:+1.10, series:sparkSeries(72,2.0,0.7),
    marketCap:"€26.4B", revenue:"€16.2B", revenueGrowth:"+8.4%", ebitda:"€7.1B", ebitdaMargin:"43.8%",
    debt:"—", cash:"€8.4B", creditRating:"A+", ratingAgency:"S&P", ratingTrend:"positive",
    employees:10840, employeeGrowth:"+3.1%", headcountSeries:[10510,10580,10650,10710,10760,10800,10820,10840],
    fundingStatus:"Public",
    news:[
      { src:"FT",        t:"DNB launches Norway's first fully-cloud retail bank stack on Azure", at:"1d", sent:"pos" },
      { src:"Finextra",  t:"DORA / NIS2 driving €600M Nordic bank cloud spend", at:"5d", sent:"neu" },
      { src:"Bloomberg", t:"DNB CFO: \"50% of cap-ex on tech through 2027\"", at:"2w", sent:"pos" },
    ],
    hiring:[
      { role:"Cloud Platform Lead", team:"Cloud Banking", n:1, since:"1w", urgent:true },
      { role:"Site Reliability Eng",team:"Platform",      n:6, since:"2w" },
    ],
    triggers:[
      { kind:"funding", text:"50% cap-ex on tech — budget secured", weight:10 },
      { kind:"reg",     text:"DORA + NIS2 — landing zone is path", weight:9 },
      { kind:"deal",    text:"First-of-kind in Norway — reference value", weight:8 },
    ],
    decisionUnit:[
      { name:"Erika Solberg", role:"CTO",        init:"ES", power:"Decision",   sent:"warm", weight:0.84 },
      { name:"Lars Hagen",    role:"Head of Cloud",init:"LH",power:"Champion",   sent:"hot",  weight:0.9 },
      { name:"Ingrid Bø",     role:"CFO",         init:"IB", power:"Approver",  sent:"warm", weight:0.7 },
    ],
    competitors:[
      { name:"Mantu", us:true, score:[84,82,72,76,72,76], price:"€2.70M", strength:"Cloud-native banking", color:"var(--brand-primary)" },
      { name:"EY",            score:[82,76,90,80,82,68], price:"€3.10M", strength:"Banking advisory",    color:"#7C3AED" },
      { name:"KPMG",          score:[78,74,88,82,80,72], price:"€2.95M", strength:"Local presence",      color:"#0E7490" },
    ],
    radarAxes:["Tech depth","Delivery","Scale","Local presence","Relationships","Price"],
    win:{ probability:40, breakdown:[
      { f:"Champion (Lars Hagen)",         w:+16 },
      { f:"DORA pressure",                  w:+9 },
      { f:"EY incumbent on advisory",       w:-10 },
      { f:"Discovery still open",           w:-7 },
    ]},
  },
};

window.LIVE_SOURCES = [
  { name:"Bloomberg",  status:"ok",   pull:"3m" },
  { name:"Crunchbase", status:"ok",   pull:"7m" },
  { name:"LinkedIn",   status:"ok",   pull:"12m" },
  { name:"S&P CapIQ",  status:"ok",   pull:"1h" },
  { name:"D&B Hoovers",status:"ok",   pull:"2h" },
  { name:"GDELT",      status:"ok",   pull:"5m" },
  { name:"Dust MCP",   status:"ok",   pull:"live" },
];
