#!/usr/bin/env bash
# =============================================================================
# bootstrap-production.sh
# BidStack 360° — First-time production environment setup
#
# Usage: bash scripts/ops/bootstrap-production.sh
#
# What it does:
#   1. Reads .env.production.template and prompts for each missing value
#   2. Writes a populated .env.production (never committed to git)
#   3. Verifies: DB connection, Redis connection, Stripe webhook signature,
#      Clerk SSO connectivity
#
# Requirements: curl, psql (or pg_isready), redis-cli, node 24+
# =============================================================================

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m' # No Color

TEMPLATE_FILE=".env.production.template"
OUTPUT_FILE=".env.production"

log_info()    { echo -e "${BLUE}[INFO]${NC}  $1"; }
log_ok()      { echo -e "${GREEN}[OK]${NC}    $1"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC}  $1"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $1"; }
log_section() { echo -e "\n${BOLD}${BLUE}=== $1 ===${NC}"; }

prompt_value() {
  local key="$1"
  local description="$2"
  local is_secret="${3:-false}"
  local current_value="${4:-}"

  if [[ -n "$current_value" ]]; then
    echo -e "  ${GREEN}✓${NC} $key already set (from template or environment)"
    echo "$current_value"
    return
  fi

  if [[ "$is_secret" == "true" ]]; then
    read -rsp "  Enter $description (hidden): " value
    echo
  else
    read -rp "  Enter $description: " value
  fi

  if [[ -z "$value" ]]; then
    log_warn "$key is empty — continuing, but this may cause failures"
  fi
  echo "$value"
}

confirm() {
  local message="$1"
  read -rp "${YELLOW}$message${NC} [y/N]: " response
  [[ "$response" =~ ^[Yy]$ ]]
}

# =============================================================================
# Pre-flight
# =============================================================================
log_section "Pre-flight checks"

if [[ ! -f "$TEMPLATE_FILE" ]]; then
  log_error "$TEMPLATE_FILE not found. Run this script from the project root."
  exit 1
fi

if [[ -f "$OUTPUT_FILE" ]]; then
  log_warn "$OUTPUT_FILE already exists."
  if ! confirm "Overwrite it?"; then
    log_info "Aborted. Existing $OUTPUT_FILE preserved."
    exit 0
  fi
fi

# Verify required CLI tools
MISSING_TOOLS=()
for tool in curl node; do
  command -v "$tool" &>/dev/null || MISSING_TOOLS+=("$tool")
done

if [[ ${#MISSING_TOOLS[@]} -gt 0 ]]; then
  log_error "Missing required tools: ${MISSING_TOOLS[*]}"
  log_error "Install them before running this script."
  exit 1
fi

log_ok "All required tools found"

# =============================================================================
# Step 1: Populate .env.production from template + prompts
# =============================================================================
log_section "Step 1: Environment variables"
log_info "Reading template from $TEMPLATE_FILE"
log_info "You will be prompted for any unset values."
echo

declare -A env_values
declare -A env_comments

# Parse template — capture comments and values
while IFS= read -r line || [[ -n "$line" ]]; do
  # Skip blank lines — preserve in output
  if [[ -z "$line" ]]; then
    env_comments["__blank_${RANDOM}"]=""
    continue
  fi

  # Comment-only lines — preserve
  if [[ "$line" =~ ^# ]]; then
    env_comments["__comment_${RANDOM}"]="$line"
    continue
  fi

  # KEY=value lines
  if [[ "$line" =~ ^([A-Z_][A-Z0-9_]*)=(.*)$ ]]; then
    key="${BASH_REMATCH[1]}"
    val="${BASH_REMATCH[2]}"

    # Strip surrounding quotes if present
    val="${val%\"}"
    val="${val#\"}"
    val="${val%\'}"
    val="${val#\'}"

    # If value looks like a placeholder (CHANGEME, TODO, empty, or <...>), prompt
    if [[ -z "$val" || "$val" == "CHANGEME" || "$val" == "TODO" || "$val" =~ ^\<.*\>$ ]]; then
      is_secret=false
      description="$key"
      if [[ "$key" =~ (SECRET|KEY|TOKEN|PASSWORD|DSN|URL|SIGNING) ]]; then
        is_secret=true
        description="$key (secret)"
      fi
      echo -e "  ${YELLOW}→${NC} $key requires a value:"
      new_val=$(prompt_value "$key" "$description" "$is_secret" "")
      env_values["$key"]="$new_val"
    else
      env_values["$key"]="$val"
      log_ok "$key = [set from template]"
    fi
  fi
done < "$TEMPLATE_FILE"

# Write output file
{
  echo "# BidStack 360° — Production Environment"
  echo "# Generated by scripts/ops/bootstrap-production.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  echo "# DO NOT COMMIT THIS FILE"
  echo ""
  for key in "${!env_values[@]}"; do
    echo "${key}=\"${env_values[$key]}\""
  done
} > "$OUTPUT_FILE"

chmod 600 "$OUTPUT_FILE"
log_ok "$OUTPUT_FILE written (mode 600)"

# Verify it's in .gitignore
if grep -q "$OUTPUT_FILE" .gitignore 2>/dev/null; then
  log_ok "$OUTPUT_FILE is in .gitignore"
else
  log_warn "$OUTPUT_FILE is NOT in .gitignore — add it immediately!"
  echo ".env.production" >> .gitignore
  log_info "Added $OUTPUT_FILE to .gitignore automatically"
fi

# =============================================================================
# Step 2: Source the new env file
# =============================================================================
log_section "Step 2: Load environment"
# shellcheck disable=SC1090
set -a; source "$OUTPUT_FILE"; set +a
log_ok "Environment loaded"

# =============================================================================
# Step 3: Verify PostgreSQL connection
# =============================================================================
log_section "Step 3: Database connection"

if [[ -z "${DATABASE_URL:-}" ]]; then
  log_warn "DATABASE_URL is not set — skipping DB check"
else
  log_info "Testing PostgreSQL connection..."

  if command -v pg_isready &>/dev/null; then
    # Extract host and port from DATABASE_URL
    DB_HOST=$(node -e "const u=new URL(process.env.DATABASE_URL); console.log(u.hostname)" 2>/dev/null || echo "localhost")
    DB_PORT=$(node -e "const u=new URL(process.env.DATABASE_URL); console.log(u.port||5432)" 2>/dev/null || echo "5432")

    if pg_isready -h "$DB_HOST" -p "$DB_PORT" -t 10 &>/dev/null; then
      log_ok "PostgreSQL is reachable at $DB_HOST:$DB_PORT"
    else
      log_error "PostgreSQL NOT reachable at $DB_HOST:$DB_PORT"
      log_error "Check: (a) DATABASE_URL is correct, (b) firewall rules allow access, (c) DB server is running"
    fi
  else
    # Fallback: use node to attempt connection
    log_info "pg_isready not found — using node connection test"
    node -e "
      const { Client } = require('pg');
      const c = new Client({ connectionString: process.env.DATABASE_URL, connectionTimeoutMillis: 10000 });
      c.connect()
        .then(() => { console.log('Connected'); c.end(); process.exit(0); })
        .catch(e => { console.error('Failed:', e.message); process.exit(1); });
    " && log_ok "PostgreSQL connection successful" || log_error "PostgreSQL connection failed — check DATABASE_URL"
  fi
fi

# =============================================================================
# Step 4: Verify Redis connection
# =============================================================================
log_section "Step 4: Redis connection"

if [[ -z "${REDIS_URL:-}" ]]; then
  log_warn "REDIS_URL is not set — skipping Redis check"
else
  log_info "Testing Redis connection..."

  REDIS_HOST=$(node -e "const u=new URL(process.env.REDIS_URL); console.log(u.hostname)" 2>/dev/null || echo "localhost")
  REDIS_PORT=$(node -e "const u=new URL(process.env.REDIS_URL); console.log(u.port||6379)" 2>/dev/null || echo "6379")

  if command -v redis-cli &>/dev/null; then
    PING_RESULT=$(redis-cli -h "$REDIS_HOST" -p "$REDIS_PORT" PING 2>/dev/null || echo "FAILED")
    if [[ "$PING_RESULT" == "PONG" ]]; then
      log_ok "Redis is reachable at $REDIS_HOST:$REDIS_PORT — PONG received"
    else
      log_error "Redis NOT responding at $REDIS_HOST:$REDIS_PORT (got: $PING_RESULT)"
    fi
  else
    # Fallback: TCP check via curl
    if curl -s --connect-timeout 5 "redis://$REDIS_HOST:$REDIS_PORT" &>/dev/null; then
      log_ok "Redis port is open at $REDIS_HOST:$REDIS_PORT (full PING not verified — install redis-cli for full check)"
    else
      log_warn "Cannot reach Redis at $REDIS_HOST:$REDIS_PORT — install redis-cli for accurate check"
    fi
  fi
fi

# =============================================================================
# Step 5: Verify Stripe webhook secret format
# =============================================================================
log_section "Step 5: Stripe webhook secret"

if [[ -z "${STRIPE_WEBHOOK_SECRET:-}" ]]; then
  log_warn "STRIPE_WEBHOOK_SECRET is not set — skipping"
elif [[ "${STRIPE_WEBHOOK_SECRET}" =~ ^whsec_ ]]; then
  log_ok "STRIPE_WEBHOOK_SECRET format is valid (starts with whsec_)"
  # Verify it's a live key vs test key (test keys start with whsec_ too — check STRIPE_SECRET_KEY instead)
  if [[ "${STRIPE_SECRET_KEY:-}" =~ ^sk_test_ ]]; then
    log_warn "STRIPE_SECRET_KEY starts with sk_test_ — you are in TEST mode. Switch to sk_live_ for production."
  elif [[ "${STRIPE_SECRET_KEY:-}" =~ ^sk_live_ ]]; then
    log_ok "STRIPE_SECRET_KEY is a live key — production mode"
  else
    log_warn "STRIPE_SECRET_KEY format unexpected — expected sk_live_ or sk_test_"
  fi
else
  log_error "STRIPE_WEBHOOK_SECRET must start with 'whsec_' — current value has unexpected format"
fi

# =============================================================================
# Step 6: Verify Clerk SSO connectivity
# =============================================================================
log_section "Step 6: Clerk SSO"

if [[ -z "${CLERK_SECRET_KEY:-}" ]]; then
  log_warn "CLERK_SECRET_KEY is not set — skipping Clerk check"
else
  log_info "Testing Clerk API connectivity..."
  HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
    --max-time 10 \
    -H "Authorization: Bearer ${CLERK_SECRET_KEY}" \
    "https://api.clerk.com/v1/users?limit=1" 2>/dev/null || echo "000")

  case "$HTTP_STATUS" in
    200) log_ok "Clerk API responded 200 — credentials valid" ;;
    401) log_error "Clerk API returned 401 — CLERK_SECRET_KEY is invalid" ;;
    403) log_error "Clerk API returned 403 — check Clerk instance is production (not dev)" ;;
    000) log_warn "Clerk API unreachable — check network connectivity" ;;
    *)   log_warn "Clerk API returned unexpected status: $HTTP_STATUS" ;;
  esac
fi

# =============================================================================
# Step 7: Final summary
# =============================================================================
log_section "Bootstrap complete"

echo ""
echo -e "  ${BOLD}Next steps:${NC}"
echo "  1. Fix any [ERROR] items above before proceeding"
echo "  2. Run: pnpm db:migrate:deploy  — apply migrations (non-interactive; prod-safe)"
echo "  3. Run: pnpm db:seed     — seed lookup tables (roles, plan tiers, etc.) if first run"
echo "  4. Run: pnpm build       — build all packages"
echo "  5. Start: pnpm start:api + pnpm start:worker"
echo "  6. Verify: curl https://app.bidstack.com/api/health"
echo "  7. Run scripts/ops/deploy-checklist.sh for final pre-launch gate"
echo ""
echo -e "  ${GREEN}${BOLD}$OUTPUT_FILE is ready. Keep it secret. Keep it safe.${NC}"
