const COMPANY_DOMAINS: Record<string, string> = {
  'CI Financial': 'ci.com',
  'Logistec Corporation': 'logistec.com',
  'Rush University System for Health': 'rush.edu',
  MAPFRE: 'mapfre.com',
  MAHLE: 'mahle.com',
  Aritzia: 'aritzia.com',
  NOS: 'nos.pt',
  'DNB Bank': 'dnb.no',
  Mantu: 'mantu.com',
};

const COMPANY_WEBSITES: Record<string, string> = {
  'CI Financial': 'https://www.ci.com/',
  'Logistec Corporation': 'https://www.logistec.com/',
  'Rush University System for Health': 'https://www.rush.edu/',
  MAPFRE: 'https://www.mapfre.com/',
  MAHLE: 'https://www.mahle.com/',
  Aritzia: 'https://www.aritzia.com/',
  NOS: 'https://www.nos.pt/',
  'DNB Bank': 'https://www.dnb.no/',
  Mantu: 'https://mantu.com/',
};

const DEFAULT_WIDGETS: Array<z.infer<typeof DashboardWidget>> = [
  {
    id: 'widget-pipeline',
    kind: 'pipeline_funnel',
    title: 'Pipeline Funnel',
    x: 0,
    y: 0,
    w: 4,
    h: 3,
    config: {},
  },
  {
    id: 'widget-forecast',
    kind: 'revenue_forecast',
    title: 'Revenue Forecast',
    x: 4,
    y: 0,
    w: 4,
    h: 3,
    config: {},
  },
  {
    id: 'widget-companies',
    kind: 'company_grid',
    title: 'Company Grid',
    x: 8,
    y: 0,
    w: 4,
    h: 3,
    config: {},
  },
  {
    id: 'widget-insights',
    kind: 'ai_insights_feed',
    title: 'AI Insights Feed',
    x: 0,
    y: 3,
    w: 6,
    h: 3,
    config: {},
  },
  {
    id: 'widget-activity',
    kind: 'activity_timeline',
    title: 'Activity Timeline',
    x: 6,
    y: 3,
    w: 6,
    h: 3,
    config: {},
  },
];
