// Brief drawer for "Ask Dust" actions. Calls
// POST /api/opportunities/:id/brief and renders the returned markdown.
// The endpoint is server-stubbed today; this UI stays valid when the
// backend swaps to a real Dust agent — only `model` and `tokens` change.

import { useEffect } from 'react';
import { useTranslation } from 'react-i18next';

import { Button } from '@/components/ui/Button';
import { Dialog, DialogContent } from '@/components/ui/Dialog';
import { ErrorState, LoadingSkeleton } from '@/components/ui/StateMessages';
import { useOpportunityBrief } from '@/hooks/useOpportunityBrief';

interface Props {
  opportunityId: string | undefined;
  opportunityLabel: string;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function BriefingDialog({ opportunityId, opportunityLabel, open, onOpenChange }: Props) {
  const { t } = useTranslation('crm');
  const brief = useOpportunityBrief(opportunityId);

  // Auto-trigger generation on open, then drop the state when the dialog
  // closes so re-opening it always fetches fresh — briefs are time-sensitive
  // and a 5-minute-old one is stale.
  useEffect(() => {
    if (open && opportunityId) brief.mutate();
    if (!open) brief.reset();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, opportunityId]);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      {open ? (
        <DialogContent
          title={t('briefing.title', 'Brief: {{label}}', { label: opportunityLabel })}
          description={t(
            'briefing.description',
            'Executive summary generated by Dust (stubbed locally without DUST_API_KEY).',
          )}
        >
          {brief.isPending ? (
            <LoadingSkeleton rows={6} />
          ) : brief.isError ? (
            <ErrorState
              title={t('briefing.errorTitle', "Couldn't generate brief")}
              message={
                brief.error instanceof Error
                  ? brief.error.message
                  : t('briefing.errorUnknown', 'Unknown error')
              }
            />
          ) : brief.data ? (
            <>
              <pre
                className="whitespace-pre-wrap rounded-md bg-[var(--surface-sunken)] p-4 text-xs text-[var(--fg-primary)] font-mono leading-relaxed"
                aria-label={t('briefing.contentAriaLabel', 'Brief content')}
              >
                {brief.data.brief}
              </pre>
              <div className="mt-3 flex items-center justify-between text-[11px] text-[var(--fg-tertiary)]">
                <span>
                  {t('briefing.modelMeta', 'Model {{model}} · {{tokens}} tokens', {
                    model: brief.data.model,
                    tokens: brief.data.tokens,
                  })}
                </span>
                <div className="flex gap-2">
                  <Button
                    size="sm"
                    variant="secondary"
                    onClick={() => void navigator.clipboard.writeText(brief.data!.brief)}
                  >
                    {t('briefing.copy', 'Copy')}
                  </Button>
                  <Button size="sm" variant="secondary" onClick={() => brief.mutate()}>
                    {t('briefing.regenerate', 'Regenerate')}
                  </Button>
                </div>
              </div>
            </>
          ) : null}
        </DialogContent>
      ) : null}
    </Dialog>
  );
}
